---
# tasks file for update_domain_user
- name: query domain user
  win_domain_user:
    name: "{{ ad_username }}"
    state: query
    domain_username: "{{ ad_domain_username }}"
    domain_password: "{{ ad_domain_password }}"
    domain_server: "{{ ad_domain_server }}"
  register: ad_user

- debug:
    msg: "{{ ad_user }}"
  when: ad_user_state == "query"

- name: update domain user
  win_domain_user:
    name: "{{ ad_username }}"
    state: "{{ ad_user_state }}"
    enabled: "{{ ad_acct_enabled | default(omit) }}"
    password: "{{ ad_user_password | default(omit) }}"
    groups: "{{ ad_group_list | default(omit) }}"
    groups_action: replace
    domain_username: "{{ ad_domain_username }}"
    domain_password: "{{ ad_domain_password }}"
    domain_server: "{{ ad_domain_name }}"
  when: ad_user_state != "query"